name: mazes
channels:
  - conda-forge
  - nodefaults
dependencies:
  # C++ Toolchain & Build System
  - cxx-compiler
  - cmake >=3.25
  - make
  - pkg-config

  # Libraries for Image Processing & Compression
  - libpng
  - zlib

  # OpenCL Vendor-Agnostic GPU/CPU Development
  - opencl-headers
  - ocl-icd
  - clinfo
  - clhpp
  - pocl

variables:
  OCL_ICD_VENDORS: /etc/OpenCL/vendors
